variable "subscription_id" {
  description = "Azure subscription ID used by the azurerm provider."
  type        = string
  sensitive   = true
}

variable "location" {
  description = "Azure region for SOA Intelligence DEV resources."
  type        = string
  default     = "eastus2"
}

variable "project_name" {
  description = "Stable project name used for resource naming and tags."
  type        = string
  default     = "soa-intelligence"
}

variable "environment" {
  description = "Deployment environment."
  type        = string
  default     = "dev"
}

variable "postgresql_administrator_login" {
  description = "Bootstrap PostgreSQL administrator login. Password is generated by Terraform and remains sensitive state data."
  type        = string
  default     = "soaadmin"
}

variable "postgresql_version" {
  description = "PostgreSQL major version."
  type        = string
  default     = "17"
}

variable "postgresql_sku_name" {
  description = "Development compute SKU."
  type        = string
  default     = "B_Standard_B1ms"
}

variable "postgresql_storage_mb" {
  description = "Allocated storage in MB."
  type        = number
  default     = 32768
}

variable "backup_retention_days" {
  description = "Backup retention for the development server."
  type        = number
  default     = 7

  validation {
    condition     = var.backup_retention_days >= 7 && var.backup_retention_days <= 35
    error_message = "backup_retention_days must be between 7 and 35."
  }
}

variable "migration_worker_image" {
  description = "Immutable SOA Intelligence Worker OCI reference used only by the private A2 migration job. Must be digest-pinned."
  type        = string

  validation {
    condition     = can(regex("@sha256:[0-9a-f]{64}$", var.migration_worker_image))
    error_message = "migration_worker_image must be an immutable OCI reference pinned by sha256 digest."
  }
}

variable "ghcr_username" {
  description = "GHCR username used for authenticated private image pull by the A2 migration job."
  type        = string
  sensitive   = true
}

variable "ghcr_token" {
  description = "Read-only GHCR token used only as a Container Apps Job registry secret. Never output."
  type        = string
  sensitive   = true
}

variable "tags" {
  description = "Additional tags merged with mandatory SOA Intelligence tags."
  type        = map(string)
  default     = {}
}
